#!/usr/bin/python3

from alpha_vantage.timeseries import TimeSeries

symbols = ["GOOGL", "APPL"]

for symbol in symbols:
    ts = TimeSeries(key="your alpha_vantage key")
    data, meta_data = ts.get_monthly(symbol)
    for key in data:
        for year in desired_years:
            if year in key:
                print("P " + key.replace("-", "/") + " " + symbol + " " + data[key]["4. close"] + " USD")
